import { create } from "zustand";

export type ViewType =
  | "login"
  | "dashboard"
  | "employee-detail"
  | "employee-form"
  | "notifications"
  | "settings";

interface AppUser {
  id: string;
  email: string;
  name: string;
  role: string;
  darkMode: boolean;
}

export interface WarningItem {
  id: string;
  employeeId: string;
  employeeName: string;
  reason: string;
  isAutoGenerated: boolean;
  absentDates: string | null;
  read: boolean;
  createdBy: string | null;
  createdAt: string;
  updatedAt: string;
  employee?: {
    fullName: string;
    employeeId: string;
    position: string | null;
    companyName: string | null;
    photoUrl: string | null;
  };
}

export interface FineItem {
  id: string;
  employeeId: string;
  employeeName: string;
  reason: string;
  amount: number;
  read: boolean;
  createdBy: string | null;
  createdAt: string;
  updatedAt: string;
  employee?: {
    fullName: string;
    employeeId: string;
    position: string | null;
    companyName: string | null;
    photoUrl: string | null;
  };
}

interface AppState {
  currentView: ViewType;
  selectedEmployeeId: string | null;
  searchQuery: string;
  darkMode: boolean;
  user: AppUser | null;
  sidebarOpen: boolean;
  pendingDeleteRequestId: string | null;
  pendingDeleteEmployeeId: string | null;

  // Notification system
  notificationsTab: "requests" | "warnings" | "fines";
  highlightWarningId: string | null;
  highlightFineId: string | null;
  popupWarnings: WarningItem[];
  popupFines: FineItem[];

  setView: (view: ViewType) => void;
  setSelectedEmployee: (id: string | null) => void;
  setSearchQuery: (query: string) => void;
  setDarkMode: (dark: boolean) => void;
  setUser: (user: AppUser | null) => void;
  setSidebarOpen: (open: boolean) => void;
  setPendingDeleteRequest: (requestId: string | null, employeeId: string | null) => void;

  // Notification setters
  setNotificationsTab: (tab: "requests" | "warnings" | "fines") => void;
  setHighlightWarning: (id: string | null) => void;
  setHighlightFine: (id: string | null) => void;
  setPopupWarnings: (warnings: WarningItem[]) => void;
  setPopupFines: (fines: FineItem[]) => void;

  reset: () => void;
}

const initialState = {
  currentView: "login" as ViewType,
  selectedEmployeeId: null as string | null,
  searchQuery: "",
  darkMode: false,
  user: null as AppUser | null,
  sidebarOpen: false,
  pendingDeleteRequestId: null as string | null,
  pendingDeleteEmployeeId: null as string | null,

  notificationsTab: "requests" as "requests" | "warnings" | "fines",
  highlightWarningId: null as string | null,
  highlightFineId: null as string | null,
  popupWarnings: [] as WarningItem[],
  popupFines: [] as FineItem[],
};

export const useAppStore = create<AppState>((set) => ({
  ...initialState,
  setView: (view) => set({ currentView: view, sidebarOpen: false }),
  setSelectedEmployee: (id) => set({ selectedEmployeeId: id }),
  setSearchQuery: (query) => set({ searchQuery: query }),
  setDarkMode: (dark) => set({ darkMode: dark }),
  setUser: (user) => set({ user }),
  setSidebarOpen: (open) => set({ sidebarOpen: open }),
  setPendingDeleteRequest: (requestId, employeeId) =>
    set({ pendingDeleteRequestId: requestId, pendingDeleteEmployeeId: employeeId }),

  // Notification setters
  setNotificationsTab: (tab) => set({ notificationsTab: tab }),
  setHighlightWarning: (id) => set({ highlightWarningId: id }),
  setHighlightFine: (id) => set({ highlightFineId: id }),
  setPopupWarnings: (warnings) => set({ popupWarnings: warnings }),
  setPopupFines: (fines) => set({ popupFines: fines }),

  reset: () => set(initialState),
}));
