import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";

export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams;
    const readFilter = searchParams.get("read");

    const where: Record<string, unknown> = {};
    if (readFilter !== null && readFilter !== "") {
      where.read = readFilter === "true";
    }

    const warnings = await db.warning.findMany({
      where,
      orderBy: { createdAt: "desc" },
      include: {
        employee: {
          select: {
            fullName: true,
            employeeId: true,
            position: true,
            companyName: true,
            photoUrl: true,
            phone: true,
            nationality: true,
            idNumber: true,
          },
        },
      },
    });
    return NextResponse.json(warnings);
  } catch (error) {
    console.error("Warnings GET error:", error);
    return NextResponse.json({ error: "Failed to fetch warnings" }, { status: 500 });
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { employeeId, employeeName, reason, isAutoGenerated, absentDates, createdBy } = body;

    if (!employeeId || !employeeName || !reason) {
      return NextResponse.json({ error: "employeeId, employeeName, and reason are required" }, { status: 400 });
    }

    const warning = await db.warning.create({
      data: {
        employeeId,
        employeeName,
        reason,
        isAutoGenerated: isAutoGenerated || false,
        absentDates: absentDates || null,
        createdBy: createdBy || null,
      },
    });

    return NextResponse.json(warning, { status: 201 });
  } catch (error) {
    console.error("Warnings POST error:", error);
    return NextResponse.json({ error: "Failed to create warning" }, { status: 500 });
  }
}

export async function PUT(request: NextRequest) {
  try {
    const body = await request.json();
    const { id, read } = body;

    if (!id) {
      return NextResponse.json({ error: "Warning id is required" }, { status: 400 });
    }

    const warning = await db.warning.update({
      where: { id },
      data: { read: read !== undefined ? read : true },
    });

    return NextResponse.json(warning);
  } catch (error) {
    console.error("Warnings PUT error:", error);
    return NextResponse.json({ error: "Failed to update warning" }, { status: 500 });
  }
}
