import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";

// ============================================================
// STAR RATING CALCULATION
// ============================================================
async function recalculateStarRating(employeeId: string) {
  try {
    const now = new Date();
    const currentMonth = now.getMonth() + 1;
    const currentYear = now.getFullYear();
    const mm = String(currentMonth).padStart(2, "0");
    const yyyy = String(currentYear);

    const monthAttendance = await db.attendance.findMany({
      where: { employeeId, date: { endsWith: `-${mm}-${yyyy}` } },
    });

    const absentCount = monthAttendance.filter((a) => a.status === "absent").length;
    const totalOvertimeHours = monthAttendance.reduce((sum, a) => sum + (a.overtimeHours || 0), 0);
    const fineCount = await db.fine.count({ where: { employeeId } });
    const warningCount = await db.warning.count({ where: { employeeId } });

    let rating = 5.0;
    if (absentCount > 2) rating -= (absentCount - 2) * 0.1;
    rating -= fineCount * 1.0;
    rating -= warningCount * 0.5;
    rating += totalOvertimeHours * 0.2;
    rating = Math.max(0.0, Math.min(5.0, Math.round(rating * 10) / 10));

    await db.employee.update({ where: { id: employeeId }, data: { rating } });
  } catch (error) {
    console.error("Star rating recalculation error:", error);
  }
}

export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams;
    const readFilter = searchParams.get("read");

    const where: Record<string, unknown> = {};
    if (readFilter !== null && readFilter !== "") {
      where.read = readFilter === "true";
    }

    const warnings = await db.warning.findMany({
      where,
      orderBy: { createdAt: "desc" },
      include: {
        employee: {
          select: {
            fullName: true,
            employeeId: true,
            position: true,
            companyName: true,
            photoUrl: true,
            phone: true,
            nationality: true,
            idNumber: true,
          },
        },
      },
    });
    return NextResponse.json(warnings);
  } catch (error) {
    console.error("Warnings GET error:", error);
    return NextResponse.json({ error: "Failed to fetch warnings" }, { status: 500 });
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { employeeId, employeeName, reason, isAutoGenerated, absentDates, createdBy } = body;

    if (!employeeId || !employeeName || !reason) {
      return NextResponse.json({ error: "employeeId, employeeName, and reason are required" }, { status: 400 });
    }

    const warning = await db.warning.create({
      data: {
        employeeId,
        employeeName,
        reason,
        isAutoGenerated: isAutoGenerated || false,
        absentDates: absentDates || null,
        createdBy: createdBy || null,
      },
    });

    // Recalculate star rating for this employee
    await recalculateStarRating(employeeId);

    return NextResponse.json(warning, { status: 201 });
  } catch (error) {
    console.error("Warnings POST error:", error);
    return NextResponse.json({ error: "Failed to create warning" }, { status: 500 });
  }
}

export async function PUT(request: NextRequest) {
  try {
    const body = await request.json();
    const { id, read } = body;

    if (!id) {
      return NextResponse.json({ error: "Warning id is required" }, { status: 400 });
    }

    const warning = await db.warning.update({
      where: { id },
      data: { read: read !== undefined ? read : true },
    });

    return NextResponse.json(warning);
  } catch (error) {
    console.error("Warnings PUT error:", error);
    return NextResponse.json({ error: "Failed to update warning" }, { status: 500 });
  }
}
